export const leadManagementActions = {
    FETCH_LEAD_MANAGEMENT_DATA_LOADING: 'FETCH_LEAD_MANAGEMENT_DATA_LOADING',
    FETCH_LEAD_MANAGEMENT_DATA_SUCCESS: 'FETCH_LEAD_MANAGEMENT_DATA_SUCCESS',
    FETCH_LEAD_MANAGEMENT_DATA_FAILURE: 'FETCH_LEAD_MANAGEMENT_DATA_FAILURE',
  }